# Walking parameters
is_sim: True
use_perception: True
steps_per_meter: 50

# Step parameters
x_size: 20 # step x size (stride size)
y_size: 30 # step y size (foot y-distance from the body center)
n_step: 6 # Always Even number
z_h: 8.0 # Foot lifting height

# [0.4 ~ 1.5]
t_step: 1.5 # Step Size
# [0 ~ 0.9]
ds_time: 0.3 # Double support phase ratio, (double support phase time)/ (step_time)

# Stabilizer Gain
# [-0.1 ~ 0]
pitch_ankle_gain: -0.1 # IMU orientation to ankle pitch angle feedback
# [-0.1 ~ 0]
roll_ankle_gain: -0.1 # IMU orientation to ankle roll angle feedback
pitch_disp_gain: 0 # IMU orientation to torso x direction feedback
# [0 ~ 50]
roll_disp_gain: 1 # IMU orientation to torso y direction feedback
ax_gain: 0 # x direction acceleration feedback
# [0 ~ 5]
ay_gain: 1 # y direction acceleration feedback
